version: "3.1"

services:

  webserver:
    image: nginx:alpine
    container_name: '${CONTAINER_PREFIX}-webserver'
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
    expose:
      - 80

  mysql:
    image: mysql:5.7
    container_name: '${CONTAINER_PREFIX}-mysql'
    working_dir: /application
    volumes:
      - .:/application
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION

  php-fpm:
    build: docker/php-fpm
    container_name: '${CONTAINER_PREFIX}-php-fpm'
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

networks:
  default:
    external:
      name: nginx-proxy